# Generated by Django 4.2.3 on 2023-09-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Received', 'Received'), ('Withdraw', 'Withdraw'), ('Refund', 'Refund'), ('Request', 'Request'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
