# Generated by Django 4.2.3 on 2023-09-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Request_Sent', 'Request Sent'), ('Request_Settled', 'Request Settled'), ('Request_Processing', 'Request Processing')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Received', 'Received'), ('Withdraw', 'Withdraw'), ('Refund', 'Refund'), ('Request', 'Payment Request'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
