# Generated by Django 4.2.3 on 2023-09-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Request Sent', 'Request Sent'), ('Request Settled', 'Request Settled'), ('Request Processing', 'Request Processing')], default='Pending', max_length=100),
        ),
    ]
