# Generated by Django 4.2.3 on 2023-09-26 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=1000000000000000), django.core.validators.MaxLengthValidator(limit_value=9999999999999999)]),
        ),
    ]
